### PR TITLE
update template param to fix clang++ compiler errors

### PR DESCRIPTION
**Pull request by JerrySievert**
* changes parameter name from `mode` to `gmode`, thus fixing clang++ compilation error, which is being masked by g++
* my editor also cleaned up some whitespace, I can revert those changes if you require.

### CODE REVIEW

**Comment by JerrySievert** [comment]
note, this fixes #5

**Comment by lnikj** [comment]
Just a confirmation that this builds OK here now too. Thanks Jerry.

Nice modules Aepelzens.

**Comment by Aepelzen** [comment]
Thanks, i appreciate the effort. But like i told you a year ago, this is not the right place for your fix. The parasites firmware is not part of this repository, it is included as a subtree. If you want this to be fixed you have to submit your patch to the parasites repository.
Also, I'm no longer maintaining this, so if you want any other fixes, feel free to fork.

**Comment by JerrySievert** [comment]
I opened the PR because you have it directly committed into your repo - if you didn't, and instead used it as a submodule, I would have gone upstream.

**Pull request closed without merging**
