### PR TITLE
Update to Rack API v0.6

### PR DESCRIPTION
**Pull request by cschol**
Update plugin to Rack API v0.6 incl. updated Makefile (reference: [Repair Team](https://github.com/VCVRack/community/issues/269)).

### CODE REVIEW

**Comment by Aepelzen** [comment]
Thanks for this. I will check it out during the next couple of days.

**Comment by cschol** [comment]
You are welcome. Let us know if you need anything else.

**Comment by cschol** [comment]
There was a change in the API today, which required some more updates.

**Comment by Aepelzen** [comment]
Merged into 0.6-dev branch. Sorry that it took so long and thanks again for doing this.

**Pull request closed without merging**
